# Generated by Django 4.2.8 on 2023-12-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='animal_id',
        ),
        migrations.AddField(
            model_name='specific',
            name='species_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='animals.specie'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500)),
                ('date_performed', models.CharField(max_length=500)),
                ('animal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='animals.specific')),
            ],
        ),
        migrations.CreateModel(
            name='Genealogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100)),
                ('relation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='animals.specific')),
            ],
        ),
        migrations.AddField(
            model_name='specific',
            name='relations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='animals.genealogy'),
        ),
    ]
