# Generated by Django 4.2.8 on 2023-12-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_specie_animal_id_specific_species_id_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
